version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ExcelMapper/ExcelMapper.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netstandard1.4/publish
  - cmd: dotnet publish ./src/ExcelMapper/ExcelMapper.csproj -f netstandard1.4
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\bin\Debug\netstandard1.4\publish'
   name: ExcelMapper
   type: Auto
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/ExcelMapper.Tests/ExcelMapper.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./src/ExcelMapper.Tests
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off